# Generated by Django 3.0.6 on 2020-06-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelist',
            name='date_of_publish',
            field=models.DateTimeField(),
        ),
    ]
