# Generated by Django 3.0.6 on 2020-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200610_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelist',
            name='date_of_publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
